name: "Release"

permissions:
  contents: write
  actions: write

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch from which we make a release"
        default: "main"
        required: false

env:
  NODE_VERSION: "20.19.0"
  NPM_VERSION: "9.2.0"
  PUSH_BRANCH: ${{ inputs.branch }}
  CI: "true"
  NPM_CONFIG_FUND: "false"
  NPM_CONFIG_AUDIT: "false"
  NPM_CONFIG_PROGRESS: "false"

jobs:
  prepare:
    name: "üîß Prepare"
    runs-on: ubuntu-latest
    steps:
      - name: "üõéÔ∏è Checkout ${{ env.PUSH_BRANCH }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PUSH_BRANCH }}
          fetch-depth: 1

      - uses: ./.github/actions/init-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          npm-version: ${{ env.NPM_VERSION }}

      - uses: ./.github/actions/npm-install

      - name: "üß™ Test"
        run: |
          npm run pre:gen:proto
          npm test

      - uses: ./.github/actions/generate-build-env

      - uses: ./.github/actions/build-web

      - uses: ./.github/actions/zip-dist

      - name: "üì¶ Upload dist.zip"
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
          if-no-files-found: error
          compression-level: 0
          retention-days: 2

      - name: "üì¶ Upload build env"
        uses: actions/upload-artifact@v4
        with:
          name: build-env
          path: build_env.txt
          if-no-files-found: error
          compression-level: 0
          retention-days: 2

  release:
    name: "üöÄ Publish release"
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: "üõéÔ∏è Checkout ${{ env.PUSH_BRANCH }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PUSH_BRANCH }}
          fetch-depth: 1

      - name: "üì• Download dist-zip"
        uses: actions/download-artifact@v4
        with:
          name: dist-zip
          path: .

      - name: "üì• Download build-env"
        uses: actions/download-artifact@v4
        with:
          name: build-env
          path: .

      - name: "üóíÔ∏è Source env"
        run: cat build_env.txt >> $GITHUB_ENV

      - name: "üöÄ Create a release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.BUILD_VER }}
          name: v${{ env.BUILD_VER }}
          generate_release_notes: true
          files: dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/init-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          npm-version: ${{ env.NPM_VERSION }}

      - uses: ./.github/actions/github-setup-user

      - name: "‚úîÔ∏è Bump minor and push package.json"
        uses: ./.github/actions/bump-version
        with:
          bump: minor
          push-branch: ${{ env.PUSH_BRANCH }}

      - name: "üßπ Remove temporary artifacts"
        if: success()
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            build-env
            dist-zip
          failOnError: false
